# Generated by Django 4.0.10 on 2025-09-12 07:27

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(db_column='CNTRY_ID', max_length=100, verbose_name='Country ID')),
                ('name', models.CharField(db_column='NAME', max_length=100, verbose_name='Country Name')),
            ],
            options={
                'db_table': 'COUNTRY',
            },
        ),
        migrations.CreateModel(
            name='SourceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_db', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sourcedb',
            },
        ),
        migrations.CreateModel(
            name='SourceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('input_type', models.CharField(max_length=100)),
                ('label_name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('src_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sourcedb')),
            ],
            options={
                'db_table': 'sourceform',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_column='EMAIL', max_length=50, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(db_column='F_NAME', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(db_column='L_NAME', max_length=50, verbose_name='Last Name')),
                ('created_by', models.CharField(db_column='CREATED_BY', max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(db_column='CREATED_ON', default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='MODIFIED_ON', verbose_name='Modified On')),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', max_length=50, null=True, verbose_name='Modified By')),
                ('active', models.BooleanField(db_column='ACTIVE', default=True, verbose_name='Active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'USER',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
