# Generated by Django 4.0.10 on 2025-09-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='CODE',
            field=models.CharField(default='null', max_length=100, verbose_name='Country Code'),
        ),
    ]
