# Generated by Django 4.0.10 on 2025-09-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='CODE',
        ),
    ]
