# Generated by Django 4.0.10 on 2025-09-12 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_active_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='IS_ACTIVE', default=True, verbose_name='active'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.AutoField(db_column='CUST_ID', primary_key=True, serialize=False, verbose_name='Customer ID')),
                ('name', models.CharField(db_column='NAME', max_length=100, verbose_name='Customer Name')),
                ('street1', models.CharField(db_column='STREET1', max_length=100, verbose_name='Street 1')),
                ('street2', models.CharField(blank=True, db_column='STREET2', max_length=100, null=True, verbose_name='Street 2')),
                ('city', models.CharField(db_column='CITY', max_length=100, verbose_name='City')),
                ('region', models.CharField(db_column='REGION', max_length=100, verbose_name='Region')),
                ('phone', models.CharField(db_column='PHONE', max_length=20, verbose_name='Phone')),
                ('cust_db', models.CharField(db_column='CUST_DB', max_length=10, unique=True, verbose_name='Customer Database')),
                ('created_by', models.CharField(db_column='CREATED_BY', max_length=50, verbose_name='Created By')),
                ('created_on', models.DateTimeField(db_column='CREATED_ON', default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='MODIFIED_ON', verbose_name='Modified On')),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', max_length=50, null=True, verbose_name='Modified By')),
                ('active', models.BooleanField(db_column='ACTIVE', default=True, verbose_name='Active')),
                ('country', models.ForeignKey(db_column='COUNTRY', on_delete=django.db.models.deletion.PROTECT, to='api.country', verbose_name='Country')),
            ],
            options={
                'db_table': 'CUSTOMER',
            },
        ),
    ]
