# Generated by Django 4.0.10 on 2025-09-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_is_active_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.CharField(max_length=100, verbose_name='Country ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Country Name'),
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
