# Generated by Django 4.0.10 on 2025-09-15 04:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_country_country_id_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.CharField(max_length=50, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_db',
            field=models.CharField(max_length=10, unique=True, verbose_name='Customer Database'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified On'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street1',
            field=models.CharField(max_length=100, verbose_name='Street 1'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.CharField(max_length=50, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified On'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
