# Generated by Django 4.0.10 on 2025-09-15 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customer_active_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cust_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer', verbose_name='Customer ID'),
        ),
    ]
