# Generated by Django 4.0.10 on 2025-09-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Customer ID'),
        ),
    ]
