# Generated by Django 4.0.10 on 2025-09-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100)),
                ('object_nme', models.CharField(max_length=100)),
                ('tecname', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'objectmap',
            },
        ),
    ]
