# Generated by Django 4.2.24 on 2025-09-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_objectmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Country ID'),
        ),
    ]
