# Generated by Django 4.2.24 on 2025-09-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_country_id_alter_country_country_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Email'),
        ),
        migrations.AddConstraint(
            model_name='objectmap',
            constraint=models.UniqueConstraint(fields=('object_id', 'tecname'), name='objectmap_pk'),
        ),
    ]
