# Generated by Django 4.2.24 on 2025-09-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_user_id_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='objectmap',
            name='objectmap_pk',
        ),
        migrations.AlterUniqueTogether(
            name='objectmap',
            unique_together={('object_id', 'tecname')},
        ),
    ]
