# Generated by Django 4.2.24 on 2025-09-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_objectmap_objectmap_pk_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectMap',
        ),
    ]
