# Generated by Django 4.0.10 on 2025-09-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_objectmap'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- First, drop the existing foreign key constraint
            ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fkey;
            
            -- Clear all existing log entries since they reference the old auth_user table
            DELETE FROM django_admin_log;
            
            -- Change the user_id column type from bigint to varchar(50)
            ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE VARCHAR(50);
            
            -- Recreate the foreign key constraint with the correct type
            ALTER TABLE django_admin_log 
            ADD CONSTRAINT django_admin_log_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES "user"(email) 
            ON DELETE CASCADE;
            """,
            reverse_sql="""
            -- Reverse migration
            ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fkey;
            ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE BIGINT;
            ALTER TABLE django_admin_log 
            ADD CONSTRAINT django_admin_log_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES auth_user(id) 
            ON DELETE CASCADE;
            """
        )
    ]
