# Generated by Django 4.0.10 on 2025-09-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_fix_admin_log_user_fk'),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Fix user_groups table
            ALTER TABLE user_groups DROP CONSTRAINT IF EXISTS user_groups_user_id_fkey;
            ALTER TABLE user_groups ALTER COLUMN user_id TYPE VARCHAR(50);
            ALTER TABLE user_groups 
            ADD CONSTRAINT user_groups_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES "user"(email) 
            ON DELETE CASCADE;
            
            -- Fix user_user_permissions table
            ALTER TABLE user_user_permissions DROP CONSTRAINT IF EXISTS user_user_permissions_user_id_fkey;
            ALTER TABLE user_user_permissions ALTER COLUMN user_id TYPE VARCHAR(50);
            ALTER TABLE user_user_permissions 
            ADD CONSTRAINT user_user_permissions_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES "user"(email) 
            ON DELETE CASCADE;
            
            -- Fix any other tables that might reference the user table
            -- Check if auth_user_groups exists and fix it
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'auth_user_groups') THEN
                    ALTER TABLE auth_user_groups DROP CONSTRAINT IF EXISTS auth_user_groups_user_id_fkey;
                    ALTER TABLE auth_user_groups ALTER COLUMN user_id TYPE VARCHAR(50);
                    ALTER TABLE auth_user_groups 
                    ADD CONSTRAINT auth_user_groups_user_id_fkey 
                    FOREIGN KEY (user_id) REFERENCES "user"(email) 
                    ON DELETE CASCADE;
                END IF;
            END $$;
            
            -- Check if auth_user_user_permissions exists and fix it
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'auth_user_user_permissions') THEN
                    ALTER TABLE auth_user_user_permissions DROP CONSTRAINT IF EXISTS auth_user_user_permissions_user_id_fkey;
                    ALTER TABLE auth_user_user_permissions ALTER COLUMN user_id TYPE VARCHAR(50);
                    ALTER TABLE auth_user_user_permissions 
                    ADD CONSTRAINT auth_user_user_permissions_user_id_fkey 
                    FOREIGN KEY (user_id) REFERENCES "user"(email) 
                    ON DELETE CASCADE;
                END IF;
            END $$;
            """,
            reverse_sql="""
            -- Reverse migration
            ALTER TABLE user_groups DROP CONSTRAINT IF EXISTS user_groups_user_id_fkey;
            ALTER TABLE user_groups ALTER COLUMN user_id TYPE BIGINT;
            ALTER TABLE user_groups 
            ADD CONSTRAINT user_groups_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES auth_user(id) 
            ON DELETE CASCADE;
            
            ALTER TABLE user_user_permissions DROP CONSTRAINT IF EXISTS user_user_permissions_user_id_fkey;
            ALTER TABLE user_user_permissions ALTER COLUMN user_id TYPE BIGINT;
            ALTER TABLE user_user_permissions 
            ADD CONSTRAINT user_user_permissions_user_id_fkey 
            FOREIGN KEY (user_id) REFERENCES auth_user(id) 
            ON DELETE CASCADE;
            """
        )
    ]


