# Generated by Django 4.0.10 on 2025-10-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_fix_all_user_foreign_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100)),
                ('tecname', models.CharField(max_length=100)),
                ('object_nme', models.CharField(max_length=100)),
                ('tname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_download_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('tsv', 'TSV')], default='excel', max_length=10, verbose_name='Preferred Download Format'),
        ),
    ]
