# Generated by Django 4.2.24 on 2025-10-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_objectmap_user_preferred_download_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_download_format',
        ),
        migrations.AddField(
            model_name='user',
            name='file_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('tsv', 'TSV')], default='csv', max_length=10),
        ),
    ]
