# Generated by Django 4.2.24 on 2025-10-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_user_preferred_download_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.CharField(max_length=100, verbose_name='Country ID'),
        ),
        migrations.AddField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),

    ]
