# Generated by Django 4.2.24 on 2025-10-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_country_id_alter_country_country_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
