# Generated by Django 4.2.24 on 2025-10-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
