# Generated by Django 4.2.24 on 2025-10-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cust_id',
        ),
    ]
