# Generated by Django 4.2.24 on 2025-10-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_fix_user_foreign_keys_to_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_format',
            field=models.CharField(default='MM-DD-YYYY', max_length=10),
        ),
    ]
