# Generated by Django 4.2.24 on 2025-10-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_user_date_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('expression', models.CharField(max_length=200)),
            ],
        ),
    ]
