# Generated by Django 4.2.24 on 2025-11-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_validationrules'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='objectmap',
            table='objectmap',
        ),
    ]
