# Generated by Django 4.2.24 on 2025-11-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_objectmap_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidationRules',
        ),
    ]
