# Generated by Django 4.2.24 on 2025-11-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_delete_validationrules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('expression', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'validationrules',
            },
        ),
    ]
