# Generated by Django 4.2.24 on 2025-11-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_validationrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrules',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
