# Generated by Django 4.2.24 on 2025-11-06 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_validationrules_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_roles', to='api.customer')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='UsrRoles',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_from', models.DateField(null=True)),
                ('valid_to', models.DateField(null=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usrroles',
            },
        ),
    ]
