# Generated by Django 3.2 on 2025-11-26 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_roles_usrroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Canvas Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('configuration', models.JSONField(default=dict, verbose_name='Canvas Configuration')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canvases', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvases', to='api.customer', verbose_name='Customer')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_canvases', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Canvas',
                'verbose_name_plural': 'Canvases',
                'db_table': 'canvas',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='MigrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True, verbose_name='Job ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('progress', models.FloatField(default=0.0, verbose_name='Progress (%)')),
                ('current_step', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Step')),
                ('config', models.JSONField(default=dict, verbose_name='Job Configuration')),
                ('stats', models.JSONField(blank=True, default=dict, null=True, verbose_name='Statistics')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('started_on', models.DateTimeField(blank=True, null=True, verbose_name='Started On')),
                ('completed_on', models.DateTimeField(blank=True, null=True, verbose_name='Completed On')),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_jobs', to='api.canvas', verbose_name='Canvas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_migration_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_jobs', to='api.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Migration Job',
                'verbose_name_plural': 'Migration Jobs',
                'db_table': 'migration_job',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='MigrationJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10, verbose_name='Log Level')),
                ('message', models.TextField(verbose_name='Message')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.migrationjob', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Migration Job Log',
                'verbose_name_plural': 'Migration Job Logs',
                'db_table': 'migration_job_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CanvasNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, verbose_name='Node ID')),
                ('node_type', models.CharField(choices=[('source', 'Source'), ('transform', 'Transform'), ('destination', 'Destination')], max_length=50, verbose_name='Node Type')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('position_x', models.FloatField(verbose_name='Position X')),
                ('position_y', models.FloatField(verbose_name='Position Y')),
                ('config', models.JSONField(default=dict, verbose_name='Node Configuration')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_nodes', to='api.canvas', verbose_name='Canvas')),
            ],
            options={
                'verbose_name': 'Canvas Node',
                'verbose_name_plural': 'Canvas Nodes',
                'db_table': 'canvas_node',
                'unique_together': {('canvas', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='CanvasEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(max_length=100, verbose_name='Edge ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_edges', to='api.canvas', verbose_name='Canvas')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='api.canvasnode', verbose_name='Source Node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='api.canvasnode', verbose_name='Target Node')),
            ],
            options={
                'verbose_name': 'Canvas Edge',
                'verbose_name_plural': 'Canvas Edges',
                'db_table': 'canvas_edge',
                'unique_together': {('canvas', 'edge_id')},
            },
        ),
    ]
