# Generated by Django 3.2 on 2025-12-03 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_canvas_canvasedge_canvasnode_migrationjob_migrationjoblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('dst_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_count', models.PositiveIntegerField(default=0)),
                ('max_count', models.PositiveIntegerField(default=500)),
            ],
            options={
                'db_table': 'destination_model',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created On')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Modified On')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.customer', verbose_name='Customer')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_projects', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'db_table': 'project',
                'ordering': ['-created_on'],
                'unique_together': {('customer', 'project_name')},
            },
        ),
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('src_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dst_schema', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'source_model',
            },
        ),
        migrations.CreateModel(
            name='SourceAttribute',
            fields=[
                ('src_attr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=100)),
                ('input_type', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('widget', models.CharField(blank=True, choices=[('TextInput', 'TextInput'), ('PasswordInput', 'PasswordInput'), ('Select', 'Select'), ('Textarea', 'Textarea')], max_length=50, null=True)),
                ('required', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('depend_on', models.CharField(blank=True, max_length=100, null=True)),
                ('dependency_value', models.CharField(blank=True, max_length=100, null=True)),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.sourcemodel')),
            ],
            options={
                'db_table': 'source_attribute',
            },
        ),
        migrations.CreateModel(
            name='DestinationAttribute',
            fields=[
                ('dst_attr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('CharField', 'CharField'), ('BooleanField', 'BooleanField'), ('DateTimeField', 'DateTimeField'), ('DurationField', 'DurationField'), ('ChoiceField', 'ChoiceField'), ('PasswordField', 'PasswordField'), ('TextAreaField', 'TextAreaField')], max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('widget', models.CharField(blank=True, choices=[('TextInput', 'TextInput'), ('PasswordInput', 'PasswordInput'), ('Select', 'Select'), ('Textarea', 'Textarea')], max_length=50, null=True)),
                ('required', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('depend_on', models.CharField(blank=True, max_length=255, null=True)),
                ('dependency', models.CharField(blank=True, max_length=255, null=True)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.destinationmodel')),
            ],
            options={
                'db_table': 'destination_attribute',
            },
        ),
        migrations.AddField(
            model_name='canvas',
            name='project',
            field=models.IntegerField(blank=True, null=True, verbose_name='Project ID'),
        ),
        migrations.CreateModel(
            name='SourceConfig',
            fields=[
                ('src_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('config_data', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(auto_now_add=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('cmp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_configs', to='api.customer')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='api.sourcemodel')),
            ],
            options={
                'db_table': 'source_config',
                'unique_together': {('cmp', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='editor', max_length=20, verbose_name='Role')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added On')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_members', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.project', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'project_member',
                'ordering': ['project', 'user'],
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DestinationConfig',
            fields=[
                ('dst_config_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('config_data', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('cmp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_configs', to='api.customer')),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='api.destinationmodel')),
            ],
            options={
                'db_table': 'destination_config',
                'unique_together': {('cmp', 'name')},
            },
        ),
    ]
