# Generated by Django 3.2 on 2026-02-04 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_migrationjob_status_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvasnode',
            options={'verbose_name': 'Pipeline Node', 'verbose_name_plural': 'Pipeline Nodes'},
        ),
        migrations.RenameField(
            model_name='canvasnode',
            old_name='config',
            new_name='config_json',
        ),
        # Safe drop: column may not exist if DB was created via different path
        migrations.RunSQL(
            "ALTER TABLE canvas DROP COLUMN IF EXISTS project;",
            state_operations=[migrations.RemoveField(model_name='canvas', name='project')],
        ),
        migrations.RunSQL(
            "ALTER TABLE canvas ADD COLUMN IF NOT EXISTS project_id INTEGER NULL;",
            state_operations=[
                migrations.AddField(
                    model_name='canvas',
                    name='project_id',
                    field=models.IntegerField(blank=True, db_column='project_id', null=True, verbose_name='Project ID'),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='canvasnode',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='canvasnode',
            name='label',
        ),
        migrations.AddField(
            model_name='canvasnode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='canvasnode',
            name='input_nodes',
            field=models.JSONField(default=list, verbose_name='Input Node IDs'),
        ),
        migrations.AddField(
            model_name='canvasnode',
            name='output_metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Output Metadata (Schema)'),
        ),
        migrations.AddField(
            model_name='canvasnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='canvasnode',
            name='business_name',
            field=models.CharField(help_text='Human-friendly name shown on canvas', max_length=255, verbose_name='Business Name (Editable)'),
        ),
        migrations.AlterField(
            model_name='canvasnode',
            name='node_id',
            field=models.CharField(help_text='Immutable UUID, must not change', max_length=100, unique=True, verbose_name='Node ID (UUID)'),
        ),
        migrations.AlterField(
            model_name='canvasnode',
            name='node_name',
            field=models.CharField(blank=True, help_text='Legacy field, use business_name instead', max_length=255, null=True, verbose_name='Node Name (Legacy)'),
        ),
        migrations.AlterField(
            model_name='canvasnode',
            name='node_type',
            field=models.CharField(choices=[('SOURCE', 'Source'), ('FILTER', 'Filter'), ('PROJECTION', 'Projection'), ('JOIN', 'Join'), ('CALCULATED_COLUMN', 'Calculated Column'), ('DESTINATION', 'Destination'), ('GROUP', 'Group'), ('SORT', 'Sort'), ('UNION', 'Union'), ('AGGREGATION', 'Aggregation'), ('TRANSFORM', 'Transform')], max_length=50, verbose_name='Node Type'),
        ),
        migrations.AlterField(
            model_name='canvasnode',
            name='technical_name',
            field=models.CharField(help_text='System-generated internal name, format: {type}_{shortId}', max_length=255, verbose_name='Technical Name (Read-only)'),
        ),
        migrations.AddIndex(
            model_name='canvasnode',
            index=models.Index(fields=['canvas', 'node_id'], name='pipeline_no_canvas__47788a_idx'),
        ),
        migrations.AddIndex(
            model_name='canvasnode',
            index=models.Index(fields=['node_id'], name='pipeline_no_node_id_a797e3_idx'),
        ),
        migrations.AlterModelTable(
            name='canvasnode',
            table='pipeline_nodes',
        ),
    ]
